#version: "3.5"
#
#services:
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
#    ports:
#      - "0.0.0.0:27017:27017"
#    networks:
#      - MONGO
#    volumes:
#      - type: volume
#        source: MONGO_DATA
#        target: /data/db
#      - type: volume
#        source: MONGO_CONFIG
#        target: /data/configdb
#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_PORT: "27017"
#    ports:
#      - "0.0.0.0:8081:8081"
#    networks:
#      - MONGO
#    depends_on:
#      - mongo
#
#networks:
#  MONGO:
#    name: MONGO
#
#volumes:
#  MONGO_DATA:
#    name: MONGO_DATA
#  MONGO_CONFIG:
#    name: MONGO_CONFIG


version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network
